### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Juniorchen02** [Juniorchen02/Pet-Adoption#2]
Menambahkan halaman register, dimana pengguna membuat akun pertama kali. Berisi username, email, password dan confirm password (Masih frontend). 

Edit : Perubahan pada foto background dan navigate ke halaman Login

**Comment by Juniorchen02** [comment]
Register done, sisa backend

**Comment by Juniorchen02** [comment]
Register done, sisa backend

**Comment by alfinwalitan** [comment]
Sudah dilakukan koneksi dengan backend dan validasi cek
